apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl
  namespace: ${DEPLOY_NS}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy-inject
rules:
  - apiGroups: ["","vmoperator.vmware.com"]
    resources:
      - virtualmachines
      - secrets
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxy-kubectl
  namespace: ${DEPLOY_NS}
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
roleRef:
  kind: ClusterRole
  name: proxy-inject
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-inject
  namespace: ${DEPLOY_NS}
  labels:
    app: proxy-inject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-inject
  template:
    metadata:
      labels:
        app: proxy-inject
    spec:
      serviceAccountName: internal-kubectl
      containers:
      - image: docker-registry.kube-system.svc:5000/vmware/proxy-inject:1.0.0
        name: proxy-inject
        env:
          - name: TKC_HTTP_PROXY
            value: "${TKC_HTTP_PROXY}"
          - name: TKC_HTTPS_PROXY
            value: "${TKC_HTTPS_PROXY}"
          - name: TKC_NO_PROXY
            value: "${TKC_NO_PROXY}"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"