apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl
  namespace: ${DEPLOY_NS}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy-inject
rules:
  - apiGroups: ["","vmoperator.vmware.com"]
    resources:
      - virtualmachines
      - secrets
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxy-kubectl
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
    namespace: ${DEPLOY_NS}
roleRef:
  kind: ClusterRole
  name: proxy-inject
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: proxy-inject
spec:
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 60
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: docker-registry.kube-system.svc:5000/vmware/proxy-inject:1.0.0
            name: proxy-inject
            env:
              - name: HTTP_PROXY
                value: "${TKC_HTTP_PROXY}"
              - name: HTTPS_PROXY
                value: "${TKC_HTTPS_PROXY}"
              - name: NO_PROXY
                value: "${TKC_NO_PROXY}"
              - name: ALL_NAMESPACES
                value: "${ALL_NAMESPACES}"
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "256Mi"
                cpu: "500m"
          restartPolicy: Never
  schedule: '*/1 * * * *'
